[ phases.build ]
cmds = [
  "cd backend && npm install",
  "cd backend && npx prisma generate",
  "cd webapp && npm install",
  "cd webapp && npm run build"
]

[ phases.setup ]
nixPkgs = [ "nodejs_20", "openssl" ]

[ start ]
cmd = "cd backend && npm start"