[ phases.build ]
cmds = [
  "cd /app/webapp && npm install",
  "cd /app/webapp && npm run build"
]

[ phases.setup ]
nixPkgs = [ "nodejs_20", "openssl" ]

[ install ]
cmds = [
  "npm install",
  "npx prisma generate"
]